services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: public
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume-estudo:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-db-volume-estudo:
